auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  wal:
    enabled: true
    dir: /tmp/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 180s       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 180s           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2021-07-07
      store: aws
      object_store: aws
      schema: v11
      index:
        prefix: index_sunil_
        period: 24h

storage_config:
        aws:
                s3: s3://ap-south-1
                bucketnames: your_bucket_name
                dynamodb:
                        dynamodb_url: dynamodb://ap-south-1
compactor:
  working_directory: /loki-sunil/compactor
  shared_store: aws

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  index_tables_provisioning:
    provisioned_write_throughput: 5
    provisioned_read_throughput: 5
  chunk_tables_provisioning:
    provisioned_write_throughput: 5
    provisioned_read_throughput: 5

